services:
  - type: web
    name: kango-pair-site
    env: docker
    plan: free
    branch: main
    repo: https://github.com/SHackingmaster/Saleem-Sessions
    dockerfilePath: ./Dockerfile
    autoDeploy: true
